title: Steven Remington
email: stevenrremington@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A digital workspace for compiler infrastructure, agentic systems, and hardware.
baseurl: ""
url: "https://www.sremington.com"
theme: minima

header_pages:
  - index.md
  - about.md
  - posts.md

sass:
  style: compressed
  sass_dir: _sass

collections:
  projects:
    output: true
    permalink: /projects/:path/
  essays:
    output: true
    permalink: /essays/:path/
